app/models.py
import datetime

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login

# Два уровня секретности:
ROLE_STUDENT = 0
ROLE_TEACHER = 1


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.VARCHAR(64), index=True, unique=True)
    email = db.Column(db.VARCHAR(128), index=True, unique=True)
    password = db.Column(db.String(256))
    first_name = db.Column(db.VARCHAR(64))
    last_name = db.Column(db.VARCHAR(64))
    role = db.Column(db.SmallInteger, default=ROLE_STUDENT)
    posts = db.relationship('Post', backref='user_id', lazy='dynamic')

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def set_teacher_role(self):
        self.role = ROLE_TEACHER


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime)  # Время создания поста
    status = db.Column(db.Integer, default=0)  # Статус, показывающий, был ли пост отредактирован
    name = db.Column(db.VARCHAR(64))
    text = db.Column(db.String(1024))
    level = db.Column(db.SmallInteger, default=ROLE_STUDENT)
    author = db.Column(db.Integer, db.ForeignKey('user.id'))

    def set_timestamp(self):
        self.timestamp = datetime.datetime.now()

    def set_changed_status(self):
        self.status = 1

    def set_name(self, name):
        self.name = name

    def set_text(self, text):
        self.text = text

    def set_level(self, lvl):
        self.level = ROLE_STUDENT if lvl is False else ROLE_TEACHER

    def set_author(self, author_id):
        self.author = author_id

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostCreateForm(FlaskForm):
    id = HiddenField('ID')
    name = StringField('Название', validators=[DataRequired(), Length(min=1, max=64)])
    text = TextAreaField('Текст', validators=[DataRequired(), Length(min=1, max=1024)])
    level = BooleanField('Только для преподавателей')  # Создание записи с уровнем секретности 1 (для преподавателей)
    submit = SubmitField('Добавить')


class PostEditForm(FlaskForm):
    id = HiddenField('ID')
    name = StringField('Название', validators=[DataRequired(), Length(min=1, max=64)])
    text = TextAreaField('Текст', validators=[DataRequired(), Length(min=1, max=1024)])
    submit = SubmitField('Изменить')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Пожалуйста, войдите, чтобы получить доступ к этой странице'
bootstrap = Bootstrap()


# security = Security()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    # Flask security
    # from app.models import Role, User
    # user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    # security.init_app(app, user_datastore)

    # Blueprints
    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp, url_prefix='/error')

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.post import bp as post_bp
    app.register_blueprint(post_bp, url_prefix='/posts')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from flask_login import login_required

from app.main import bp


@bp.route('/')
@bp.route('/index')
@login_required
def index():
    return render_template('index.html', title='Домашняя страница')

app/post/__init__.py
from flask import Blueprint

bp = Blueprint('post', __name__, static_folder='static')

from app.post import routes

app/post/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from werkzeug.datastructures import MultiDict

from app import db
from app.models import Post
from app.post import bp
from app.post.forms import PostCreateForm, PostEditForm


@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = PostCreateForm()
    if form.validate_on_submit():
        post = Post.query.filter_by(name=form.name.data).first()
        if post:
            flash('Пост с таким названием уже существует')
            return redirect(url_for('post.create'))
        post = Post(name=form.name.data, text=form.text.data)
        post.set_timestamp()  # Установка времени создания поста
        if current_user.role == 1:
            post.set_level(1)
        else:
            post.set_level(form.level.data)  # Установка уровня секретности для поста
        post.set_author(current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Пост создан!')
        return redirect(url_for('post.list'))
    return render_template('post/post_create.html', title='Новый пост', form=form, role=current_user.role)


@bp.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.filter_by(id=id).first()

    if post is None:
        flash('Пост не найден')
        return redirect(url_for('post.list'))

    if current_user.role != post.level:
        flash('Нет прав для редактирования')
        return redirect(url_for('post.list'))

    form = PostEditForm(MultiDict([('id', post.id), ('name', post.name), ('text', post.text)]))

    if request.form.get('name'):
            post.set_changed_status()
            post.set_name(request.form.get("name"))
            post.set_text(request.form.get("text"))

            db.session.commit()
            flash('Пост успешно изменен')
            return redirect(url_for('post.list'))
    return render_template('post/post_edit.html', title='Изменение поста', form=form, post=post, role=current_user.role)


@bp.route('/list')
@login_required
def list():
    page = request.args.get('page', 1, type=int)
    if current_user.role == 0:
        posts = Post.query.filter_by(level=0).order_by(Post.timestamp.desc()).paginate(page, 12, False)
    else:
        posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, 12, False)
    next_url = url_for('post.list', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('post.list', page=posts.prev_num) if posts.has_prev else None
    return render_template('post/post_list.html', title='Список всех постов', posts=posts.items, next_url=next_url,
                           prev_url=prev_url, role=current_user.role)


@bp.route('/delete/<id>', methods=['GET'])
@login_required
def delete(id):
    post = Post.query.filter_by(id=id).first()

    if post is None:
        flash('Пост не найден')
        return redirect(url_for('post.list'))

    if current_user.role != post.level:
        flash('Нет прав для удаления')
        return redirect(url_for('post.list'))

    db.session.delete(post)
    db.session.commit()
    flash('Пост успешно удален')
    return redirect(url_for('post.list'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {% if title %}{{ title }} - Post{% else %}Post App{% endif %}
{% endblock %}

{% block metas %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Test</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Главная</a>
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('post.list') }}">Список постов</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}">Войти</a></li>
                    {% else %}
                        <li><a href="{{ url_for('post.create') }}">Добавить пост</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Выйти</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <main>
        <div class="container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block app_content %}
            {% endblock %}
        </div>
    </main>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% block app_scripts %}
    {% endblock %}
{% endblock %}

{% block styles %}
    {{ super() }}
    {% block app_styles %}
    {% endblock %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h3>Привет, {{ current_user.username }} </h3>
{% endblock %}

app/templates/post/post_create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Добавить пост</h2>
        </div>
    </div>
    <hr>
    <form action="{{ url_for('post.create') }}" method="post" class="form" role="form" id="boardForm" name="boardForm">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="form-group col-md-6">
                {{ form.id }}
                {{ wtf.form_field(form.name, id='name') }}
                {{ wtf.form_field(form.text, id='text') }}
                {% if role == 0 %}
                    {{ wtf.form_field(form.level, id='level') }}
                {% endif %}
                {{ wtf.form_field(form.submit, class='btn btn-primary') }}
            </div>
        </div>
    </form>
{% endblock %}

app/templates/post/post_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Изменить пост</h2>
        </div>
    </div>
    <hr>
    <form action="{{ url_for('post.edit', id=post.id) }}" method="post" class="form" role="form" id="boardForm" name="boardForm">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="form-group col-md-6">
                {{ form.id }}
                {{ wtf.form_field(form.name, id='name') }}
                {{ wtf.form_field(form.text, id='text') }}
                {{ wtf.form_field(form.submit, class='btn btn-primary') }}
            </div>
        </div>
    </form>
{% endblock %}

app/templates/post/post_list.html
{% extends "base.html" %}

{% block app_content %}
    <h2>Список всех постов</h2>
    {% if posts %}
        {% for postrow in posts | batch(3) %}
            <div class="row">
                {%- for post in postrow %}
                    <div class="col-md-4">
                        <div class="panel panel-primary">
                            <div class="panel-heading clearfix">
                                <h3 class="panel-title pull-left">{{ post.name }}</h3>
                                {% if role == post.level %}
                                    <a class="btn btn-sm mr-2 btn-danger pull-right" href="{{ url_for('post.delete', id=post.id) }}">Удалить</a>
                                    <a class="btn btn-sm mr-2 btn-success pull-right" href="{{ url_for('post.edit', id=post.id) }}">Редактировать</a>
                                {% endif %}
                            </div>
                            <div class="panel-body">
                                <div id="text_{{ post.id }}">{{ post.text }}</div>
                            </div>
                        </div>
                    </div>
                {%- endfor %}
            </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous{% if not prev_url %} disabled{% endif %}">
                    <a href="{{ prev_url or '#' }}">
                        <span aria-hidden="true">&larr;</span> Новые
                    </a>
                </li>
                <li class="next{% if not next_url %} disabled{% endif %} ">
                    <a href="{{ next_url or '#' }}">
                        Старые<span aria-hidden="true">&rarr;</span>
                    </a>
                </li>
            </ul>
        </nav>
    {% else %}
        <h4>Ещё не создано ни одного поста :(</h4>
        <a href="{{ url_for('post.create') }}" class="btn btn-primary">Создать сейчас!</a>
    {% endif %}
{% endblock %}